[theme]
primaryColor = "#667eea"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#161B22"
textColor = "#C9D1D9"
font = "sans serif"

[client]
showErrorDetails = false

[logger]
level = "error"

[server]
maxUploadSize = 200
